version: "3"
services:
  server:
    image: solar-api
    ports:
      - "8080:8080"
    #environment:
#      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
      #- spring.datasource.url=jdbc:mysql://sistagedb.mysql.database.azure.com/saas_schema?reconnect=true&createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=solaRadmiN3246
      - MYSQL_DATABASE=sistagedb
      - MYSQL_USER=dataadmin@sistagedb
      - MYSQL_PASSWORD=solaRadmiN3246

networks:
  springmysql-net:
