package com.solar.api.saas.service.job;

public enum EJobName {

    ACTIVATION, GENERATE, GENERATE_BY_CODE, INVOICE_BY_CODE, INVOICE_PDF_BY_CODE,
    INVOICE, INVOICE_PDF, SCHEDULED_INVOICING, POST_BILLING_CALCULATIONS_BY_CODE,
    POST_BILLING_CALCULATIONS, FILE_IMPORT_PAYMENTS, FILE_IMPORT_BILL_CREDITS, FILE_IMPORT_USERS, FILE_IMPORT_ADDRESSES, FILE_IMPORT_PAYMENT_INFOS, FILE_IMPORT_SUBSCRIPTIONS,
    BILLING_CREDITS_ETL_BATCH, AGING_REPORT_BATCH, PUBLISH_INVOICE, ROLLOVER, GENERATE_TRUE_UPS, EMAIL_TRUE_UPS, BILL_INVALIDATE,
    ADHOC_SUBSCRIPTION_TERMINATION, AUTO_SUBSCRIPTION_TERMINATION, ACH_CSV_RESIDENT, ACH_CSV_COMMERCIAL, EXPORT_CUSTOMER, DISABLE_VARIANT, DISABLE_PRODUCT, PENDING_BILLS, BULK_CALCULATE
    ,BULK_SKIP_UNSKIP,BULK_DISCOUNT,BULK_GENERATE_INVOICE,BULK_PUBLISH_INVOICE,BILLING_CREDITS_BATCH,ACTIVATE_PROJECTION,DEACTIVATE_PROJECTION,PROJECT_PROJECTION_REVENUE;
}
