package com.solar.api.saas.module.com.solar.scheduler.model;

import java.util.Arrays;

public enum EJobCheck {

    ACTIVATION("ACTIVATION"),
    GENERATION("GENERATION"),
    INVOICING("INVOICING"),
    PUBLISH_INVOICES_EMAIL("PUBLISH_INVOICES_EMAIL"),
    ROLL_OVER_ALL("ROLL_OVER_ALL"),
    AUTO_SUBSCRIPTION_TERMINATION("AUTO_SUBSCRIPTION_TERMINATION"),
    ADHOC_SUBSCRIPTION_TERMINATION("ADHOC_SUBSCRIPTION_TERMINATION"),
    NOTIFICATION_FOR_AUTO_SUBSCRIPTION_TERMINATION("NOTIFICATION_FOR_AUTO_SUBSCRIPTION_TERMINATION"),
    XCEL_BILLING_CREDITS_IMPORT("XCEL_BILLING_CREDITS_IMPORT"),
    NPV("NPV"),
    ANALYTICAL_CALCULATION("ANALYTICAL_CALCULATION"),
    STAVEM_THROUGH_CSG_IMPORT("STAVEM_THROUGH_CSG_IMPORT"),
    STAVEM_ROLES_IMPORT("STAVEM_ROLES_IMPORT"),
    HOURS_CALCULATION_BATCH("HOURS_CALCULATION_BATCH"),
    AGING_REPORT_BATCH("AGING_REPORT_BATCH"),
    INVOICE("INVOICE"),
    ADD_MONITOR_READINGS("ADD_MONITOR_READINGS"),

    GENERATE_BILLS_ON_ACTIVATION("GENERATE_BILLS_ON_ACTIVATION"),
    EGAUGE_GRAPH_DATA("EGAUGE_GRAPH_DATA"),
    SOLRENVIEW_GRAPH_DATA("SOLRENVIEW_GRAPH_DATA"),
    DATA_INGESTION_BATCH("DATA_INGESTION_BATCH"),
    MIGRATE_DATA_INGESTION_BATCH("MIGRATE_DATA_INGESTION_BATCH"),
    EMAIL_WORKFLOW("EMAIL_WORKFLOW"),
    INDIVIDUAL_INVOICING("INDIVIDUAL_INVOICING"),
    EMAIL_INVOICE("EMAIL_INVOICE"),
    DISABLE_VARIANT("DISABLE_VARIANT"),
    DISABLE_PRODUCT("DISABLE_PRODUCT"),
    PENDING_BILLS("PENDING_BILLS"),
    BULK_CALCULATE("BULK_CALCULATE"),
    UPDATE_PROJECT_STATUS("UPDATE_PROJECT_STATUS"),
    SOLAX_GRAPH_DATA("SOLAX_GRAPH_DATA"),
    SOLIS_GRAPH_DATA("SOLIS_GRAPH_DATA"),
    GOODWEE_GRAPH_DATA("GOODWEE_GRAPH_DATA"),
    TIGO_GRAPH_DATA("TIGO_GRAPH_DATA"),
    SOLAREDGE_GRAPH_DATA("SOLAREDGE_GRAPH_DATA"),
    ENPHASE_GRAPH_DATA("ENPHASE_GRAPH_DATA"),
    BILLING_CREDITS_BATCH("BILLING_CREDITS_BATCH"),
    DEACTIVATE_PROJECTION("DEACTIVATE_PROJECTION"),
    WEATHER_API("WEATHER_BATCH"),
    WEATHER_API_FOR_STORING_HOURLY_DATA_IN_DATABASE("WEATHER_API_FOR_HOURLY_DATA_STORING_IN_DATABASE"),
    WEATHER_API_TO_FETCH_DATA("WEATHER_API_FOR_FETCHING_SEVEN_DAYS_DATA"),
    ACTIVATE_PROJECTION("ACTIVATE_PROJECTION"),
    PROJECT_PROJECTION_REVENUE("PROJECT_PROJECTION_REVENUE"),

    UNDER_PERFORMANCE_JOB("UNDER_PERFORMANCE_JOB");
    String jobName;




    EJobCheck(String jobName) {
        this.jobName = jobName;
    }

    public String getType() {
        return jobName;
    }

    public static EJobCheck get(String jobName) {
        return Arrays.stream(values()).filter(value -> jobName.equalsIgnoreCase(value.jobName)).findFirst().orElse(null);
    }
}
