package com.solar.api.tenant.model.extended;

public enum ECodeTypeRefMap {
    REGISTER,MEASURE_BLOCK,ASSET_HEAD,PARTNER_HEAD,HR_HEAD,ASSET_BLOCK_DETAIL,PARTNER_BLOCK_DETAIL,HR_BLOCK_DETAIL,
    PROJECT_HEAD
}
