package com.solar.api.tenant.service.job;

public enum EJobNameTenant {

    ACTIVATION, BILLING_BY_RATE_MATRIX_HEAD_ID, BILLING_BY_SUBSCRIPTION_CODE, INVOICE_BY_SUBSCRIPTION_CODE,
    INVOICE_BY_MATRIX_ID, POST_BILLING_CALCULATIONS_BY_SUBSCRIPTION_CODE,
    POST_BILLING_CALCULATIONS_BY_RATE_MATRIX_HEAD_ID, FILE_IMPORT_PAYMENTS, FILE_IMPORT_BILL_CREDITS,
    BILLING_CREDITS_ETL, ROLLOVER;
}
